version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - "./postgre_data:/var/lib/postgresql/data"
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "senha1234"
    ports:
       - "16543:80"
    depends_on:
       - postgres
    networks:
       - postgres-compose-network


networks:
  postgres-compose-network:
    driver: bridge